### PR TITLE
Proper resources action permissions

### LINKED ISSUE #8: Proper resources action permissions
Resources are added when activities are added. Therefore permissions on this controller should ensure that a resource may be added/edited/deleted at any time that an activity may be logged.

### PR DESCRIPTION
**Pull request by amazeika**
resolve #8

### CODE REVIEW

**Comment by amazeika** [comment]
Perhaps a better option than the one proposed is to extend the activity permission and point all canAdd, canEdit and canDelete actions to parent::canAdd.

@johanjanssens thoughts?

**Comment by johanjanssens** [comment]
@amazeika Not a 100% sure what you are trying to do. If I get it right you want resources to only be editable or deletable if an activity is addable? If so then extending from the activity permission makes sense and using the parent::canAdd().

What is the use case or flow requiring this change?

**Comment by amazeika** [comment]
@johanjanssens Exactly as you say. Made the change.

**Comment by johanjanssens** [comment]
@amazeika Can this branch be deleted?

**Comment by amazeika** [comment]
@johanjanssens Yes, I'll do so.

**Pull request merged**
